### ISSUE TITLE
createBindingConstraint is not compatible with thermal unit coëfficients

### ISSUE THREAD

**Issue by jorritvm** [rte-antares-rpackage/antaresEditObject#10]
Hi, 

At the moment the coëfficients argument (a named vector) only takes links (format "zoneA%zoneB") as an name. Can this be extended to allow thermal clusters (format "zoneA.clusterX") as well as this is possible since Antares V6.1.3?

https://github.com/rte-antares-rpackage/antaresEditObject/blob/8aa8e7810f827367f4c3b4e98baab8249f600f26/R/createBindingConstraint.R#L77

My current workaround is to make the BC on the first link I find, then to go into the ini-file using readIniFile, modify it manually and write it back using writeIni which is a bit cumbersome :-)

**Comment by pvictor** [comment]
Hello Jorrit,

Actually only coefficients containing the `%` symbol are checked to see if they are valid links.

For the moment nothing prevents you from doing : 

```r
createBindingConstraint(
  name = "myconstraint",
  overwrite = TRUE,
  values = matrix(data = rep(0, 8760 * 3), ncol = 3),
  enabled = FALSE,
  timeStep = "hourly",
  operator = "both",
  coefficients = c("fr.fr_boucht_7" = 1, "fr%it" = 0.5)
)
```

Result will be : 

```
[13]
name = myconstraint
id = myconstraint
enabled = false
type = hourly
operator = both
fr.fr_boucht_7 = 1.000000
fr%it = 0.500000
```
But no checks are performed to validate the area or the thermal cluster.
I'm not familiar with binding constraints for thermal clusters, is the syntax looks good for you ? I'll check on my side.

Victor

**Comment by jorritvm** [comment]
You're right ofcourse, tested it last week and it works. Sorry for the confusion.
