### ISSUE TITLE
createLink incompatible with Antares v7

### ISSUE THREAD

**Issue by bilalhahati** [rte-antares-rpackage/antaresEditObject#11]
"dataLink" function should be updated in order to create the necessary input data for a given link in ANTARES v7. 

In the past, a matrix with only 5 columns was needed (trans. capacity (direct) trans. capacity (indirect), impedances, hurdles cost (direct), hurdles cost (indirect)). 

With ANTARES v7, a matrix of 8 columns is needed to take into account the new parameters (i.e. loop flow, p.shift.min, p.shift.max)

**Comment by etienne-s** [comment]
Hi Bilal, thanks for the report. It just has been updated in the dev version.

**Comment by pvictor** [comment]
And it's on CRAN. Don't hesitate to open a new issue if you encounter some troubles.
