### ISSUE TITLE
createPSP not updated to antares v7

### ISSUE THREAD

**Issue by jorritvm** [rte-antares-rpackage/antaresEditObject#17]
https://github.com/rte-antares-rpackage/antaresEditObject/blob/ecf98eece4b3637c2bf57c28c20ccd02e0cb362e/R/createPSP.R#L233

Anatares 7 requires 8 columns for a link update. The function createLink() was updated (cfr. issue 11), however, when called from createPSP  > addLinksBetweenPspAndAreas a matrix of only 5 columns is provided. Please add 3 0-columns to these matrices (line 233 and line 236).

**Comment by pvictor** [comment]
Hello,
I added 3 columns with 0, tell me it works for you.
Also made the change for `editPSP` function.

Install dev version with : 

```r
remotes::install_github("rte-antares-rpackage/antaresEditObject")
```

Victor

**Comment by jorritvm** [comment]
Hi, thanks for the quick modification. However, v7 introduced another change in the links table.
Hurdle costs in antares V7 are matrix column indices 3 & 4, while they used to be 4 & 5.
In your if(v7) { } clause you therefore might want to switch the column order like this (1,2,4,5,3) before cbinding the 3 zero columns...

**Comment by pvictor** [comment]
Sorry for that, I've changed the columns order, if you can try again, thanks !

**Comment by jorritvm** [comment]
works fine, thanks!
