### ISSUE TITLE
use coherent tag numbering between antares repo

### ISSUE THREAD

**Issue by cderv** [rte-antares-rpackage/antaresEditObject#18]
See rte-antares-rpackage/antaresXpansion#29 and rte-antares-rpackage/antaresXpansion#28

This would be required to try a new deployment process internally at RTE.

**Comment by pvictor** [comment]
I updated the tag to `v0.1.7`, is it good ?

**Comment by cderv** [comment]
it worked like a charm ! 
having tags of the form `v<version-as-in-DESCRIPTION>` will launch a deployment on our internal system. 

Now we have this one ok. 

/close
