### ISSUE TITLE
Write Local data and daily max generating power for hydro

### ISSUE THREAD

**Issue by ghost** [rte-antares-rpackage/antaresEditObject#32]
Is it possible to have a function that enables the user to write local data and daily power and energy credits instead of writing these inputs manually ? 

Your help is highly appreciated. 
Thank you

**Comment by pvictor** [comment]
Hello,

Can you point to the files you want to write/edit ? in the file tree of an Antares study

Thanks,

Victor

**Comment by MahmoudMobir** [comment]
Hello, 
"\input\hydro\common\capacity\maxpower_area.txt" for max power;
"\input\hydro\prepro\region\prepro.ini" for intermonthly correlation;

I didn't find the path of the file corresponding to management option of hydro (figure belolow) : 
![image](https://user-images.githubusercontent.com/56552654/87927189-18927780-ca83-11ea-90bc-1753f7f6bde1.png)

Thanks, 

Mahmoud

**Comment by MahmoudMobir** [comment]
Dear Victor, 

Could you tell if there is a newer version of antaresEditObject that takes into account to suggested modifications ? 

Every input is highly appreciated 

BR
Mahmoud
