### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by pvictor** [rte-antares-rpackage/antaresEditObject#39]
Is package pipeR really needed ?
It seems to be used only for one function : https://github.com/rte-antares-rpackage/antaresEditObject/blob/4670738ab57db867d5b06487527db40c2290595d/R/aggregateResult.R#L613

:stuck_out_tongue: :stuck_out_tongue:
🙈

**Comment by TitouanRobert** [comment]
This is not a pipe! done on branch.

**Comment by pvictor** [comment]
Ahaha fait gaffe je surveille ce que tu fais :stuck_out_tongue_closed_eyes:

**Comment by TitouanRobert** [comment]
Mdr

Le jeu. 8 avr. 2021 à 18:17, Victor Perrier ***@***.***> a
écrit :
