### ISSUE TITLE
createBindingConstraint - issue with coefficients

### ISSUE THREAD

**Issue by ABurlin** [rte-antares-rpackage/antaresEditObject#44]
Hello,

When using createBindingConstraint, I encountered an issue with including the function in a loop. 
I want to define binding constraints for multiple different nodes (variable named 'country' in the enclosed script). I included the following instructions in a "for" loop but it does not seem to work. Is there another way to do it ?

for (country in ...){
  ...

   linkBindingConstraint <- paste0("0_battery_pmp%", country)
   
   createBindingConstraint(paste0("battery_energyLimit_", country),
                           values = cbind(rep(newBattery_Enrg, 366), rep(0, 366), rep(0, 366)),
                           timeStep = "daily",
                           operator = "less", 
                           coefficients = c(linkBindingConstraint = -1),
                           overwrite = TRUE)

}

The result in the input\bindingconstraints folder is the following : 

[181]
name = battery_energyLimit_ukni
id = battery_energylimit_ukni
enabled = true
type = daily
operator = less
linkBindingConstraint = -1.000000

Of course, Antares is unable to read linkBindingConstraint = -1.000000 which should be here 0_battery_pmp%ukni

Please note that the following alternatives did not work either : 
coefficients = c(paste0("0_battery_pmp%", country) = -1)
coefficients = paste0("0_battery_pmp%", country, " = -1")
coefficients = c(paste0("0_battery_pmp%", country, " = -1"))

Thank you, 

Arthur

**Comment by pvictor** [comment]
Hello Arthur,

Correct syntax for coefficient is:

```r
createBindingConstraint(
  ...
  coefficients = c("area1%area2" = -1),
  ...
)
```

Coefficients argument must be a named vector.

In your case it should be something like:

```r
linkBindingConstraint <- paste0("0_battery_pmp%", country)

createBindingConstraint(
  paste0("battery_energyLimit_", country),
  values = cbind(rep(newBattery_Enrg, 366), rep(0, 366), rep(0, 366)),
  timeStep = "daily",
  operator = "less",
  coefficients = setNames(-1, linkBindingConstraint),
  overwrite = TRUE
)
```

Victor

**Comment by ABurlin** [comment]
Hello Victor,

I was missing the function setNames, thank you !

Best regards,

Arthur
