### ISSUE TITLE
Creating Link with Antares 8.2 and editObject

### ISSUE THREAD

**Issue by eromano2016** [rte-antares-rpackage/antaresEditObject#51]
I am using Antares 8.2 with the  EditObject package for R.
 
After creating an new area and a new link in an Antares 8.2 study, Antares faces the following issue when opening the study :  
The program reports that it can not find a series of files (ex. node_parameters.txt) in the inputs/link/node folder. See attached picture. 

The issue doesnt appear on a 8,1 study. 

Is it related to a need for an update of EditObject in order to be compatible with Antares 8.2 ? 

Thank you for your feedback. 

![1](https://user-images.githubusercontent.com/21000377/175980219-4f90a641-dc69-4213-9846-78d36689222e.jpg)

**Comment by pvictor** [comment]
Have you tried with the the development version of {antaresEditObjet} ? You can install it with : 

```r
remotes::install_github("rte-antares-rpackage/antaresEditObject")
```
