### ISSUE TITLE
Modify the data of a cluster and recreate it completely

### ISSUE THREAD

**Issue by Maxxouxx** [rte-antares-rpackage/antaresEditObject#7]
Hello,

Is it possible to use CreateCluster() (or another function) just to modify the data of a unit (in a simple way)?
Because it is possible, but it is also required to put all the input data back in CreateCluster() to be sure it is exactly the same unit characteristics (except the one I want to change).

**Comment by pvictor** [comment]
Hi,
You can try new function `editCluster`, for example to only modify the nominal capacity : 

```r
editCluster(area = "myarea", cluster_name = "mycluster", nominalcapacity = 10600.000)
```

You're the first user of this function, feedbacks are welcome !

Victor

**Comment by Maxxouxx** [comment]
Thank you for your work, I will try it :)

Maxime

**Comment by Maxxouxx** [comment]
Hello, 

Just to say, it is working perfectly up to now ;)

Maxime

**Comment by pvictor** [comment]
Perfect! Thanks for the feedback ! I also added a method to edit links in the same way.
